### ISSUE TITLE
Cannot install via manifest

### ISSUE THREAD

**Issue by apoapostolov** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-1#1]
I get the following issue on Foundry 0.6.2.

![image](https://user-images.githubusercontent.com/4083812/84209340-99427900-aabe-11ea-9fef-157994067a95.png)

**Comment by datdamnzotz** [comment]
Man, I didn't even make an announcement!
the Zip is still uploading... Wait like 15 mins then remove/install again. : ]

**Comment by datdamnzotz** [comment]
Verified Installs are working fine. - Closing.
