### ISSUE TITLE
Modules probably archived

### ISSUE THREAD

**Issue by Plushtoast** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-1#10]
Hi, 
your audio bundles currently can not be installed via the module installer in v11.

![image](https://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/assets/44941845/97a1ddd7-70e0-4e85-95cc-dde4016de5b8)

this might be the reason. you ll probably have to create a new version in the admin panel of foundry.

thanks for maintaining these modules.

**Comment by datdamnzotz** [comment]
Naw they aren't archived!
Just not updated to the current version. I've been on the 10.x flavor for a while now and loving it.  I haven't had the need to upgrade LOL

I'll see if I can get to updating it.
Thank you for the ping and letting me know!

**Comment by datdamnzotz** [comment]
Not sure what happened in the admin console for publishing these.   They were all archived.  I removed and re-added them back in.  Looks good now.

Closing.
