### ISSUE TITLE
Error when installing via manifest

### ISSUE THREAD

**Issue by apoapostolov** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-1#2]
Hello, and sorry for rushing earlier. I found this mod via github search for foundry vtt mods, that's how I find the new gems to install before they get announced. However, even after 1.1 the manifest link is giving me errors on 0.6.2:

![image](https://user-images.githubusercontent.com/4083812/84243881-84400700-ab0b-11ea-9301-eb124eb96269.png)

**Comment by sneat** [comment]
Works from the manifest now 👍

**Comment by apoapostolov** [comment]
I confirm it is downloading now.
