### ISSUE TITLE
Compatibility with Recent 0.8.x and 0.9.x Foundry Releases?

### ISSUE THREAD

**Issue by mikelococo** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-1#5]
The compatibleCoreVersion inhttps://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/blob/master/module.json#L7 is still set to 0.8.0, which:

- Is a pre-release version of the 0.8.x series, not a stable release
- Is not the most recent in the 0.8.x stable series
- Is about to become a major release behind, as 0.9.x has had its third testing release

This is mostly a content module, and although it has a db file in it I'm not aware of any compatibility problems with more recent releases. Is there any chance of updating compatibleCoreVersion to accurately convey the module's compatibility so people know if they can safely install it on modern Foundry releases?

This applies to the other Game Audio Bundle's as well, but I won't spam tickets in each repo as they're basically just shards off this.

**Comment by datdamnzotz** [comment]
Yup behind the ball on getting the rev's out.  We are still on 0.7.10 (the reason it hasn't been bumped)
Just haven't found the time to test with 0.8x or 0.9.x yet

**Comment by datdamnzotz** [comment]
Fixed with new build for 0.8.9
