### ISSUE TITLE
No compatibility with FoundryVTT v11

### ISSUE THREAD

**Issue by Cheveyome** [datdamnzotz/FoundryVTT-Game-Audio-Bundle-1#8]
The Audio Bundle throws the following error with vtt v11:

```
Metadata validation failed for module "gAudioBundle-1": Module validation errors:
  packs: 
    0: 
      type: may not be undefined
```

**Comment by Alkhemeia** [comment]
Please Update

`Error: Unable to load valid module manifest data from "https://raw.githubusercontent.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/master/module.json"
Module validation errors:
  packs: 
    0: 
      type: may not be undefined`

**Comment by datdamnzotz** [comment]
Fixed via build https://github.com/datdamnzotz/FoundryVTT-Game-Audio-Bundle-1/releases/tag/v3.1
